# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4103071695d0608e540739a981325c7ce4f73ad4747984b9719b7dd0285ce25e8cc9f7947c925369976c1681ba1047cbdfe8d94b65d17521c952638705b9bcc7
  mailgun_api_key: <%= ENV["mailgun_api_key"] %>
  mailgun_username: <%= ENV["mailgun_username"] %>

test:
  secret_key_base: 32e6a8b8fc33a7e0bf69066f4c620c59b961d56081304adcbd5b0fdf1513efbeb413ac6edf929edbf99f42b72fb60d733c27f5a1d0f78d16fb817c52c54f8f2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 32e6a8b8fc33a7e0bf69066f4c620c59b961d56081304adcbd5b0fdf1513efbeb413ac6edf929edbf99f42b72fb60d733c27f5a1d0f78d16fb817c52c54f8f2f
  mailgun_api_key: <%= ENV["mailgun_api_key"] %>
  mailgun_username: <%= ENV["mailgun_username"] %>
